In [1]:
import numpy as np
from numpy import random

# Part A

### 1. Creating NumPy arrays

In [2]:
#a
print(np.__version__)
array1 = np.array([1,2,3,4,5])
array2 = np.array([[1,2,3],[4,5,6]])

1.18.5


In [3]:
#b
print(type(array1))
print(type(array2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
#c
print(array1.nbytes)
print(array2.nbytes)

20
24


In [5]:
#d
array2.shape

(2, 3)

In [6]:
#e
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 2. Slicing of arrays 

In [7]:
#a
array = [4, 5, 6, 3, 9, 7]
array[2:5]

[6, 3, 9]

In [8]:
#b
array =  np.array([[1, 2, 3],[4, 5, 6]])
array[:1,:2]

array([[1, 2]])

### 3. Join and splitting of NumPy Arrays  

In [9]:
#a
array1 =  [4,5,6,7]
array2 = [3,4,1]
array1+array2

[4, 5, 6, 7, 3, 4, 1]

In [10]:
#b
array1 =  np.array([[1, 2, 3],[4, 5, 6]])
array2 =  np.array([[7, 8, 9],[10,11, 12]])
np.concatenate((array1,array2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [11]:
#c
array = np.array([4, 5, 6, 3, 9])
new_array = np.array_split(array,3)
new_array

[array([4, 5]), array([6, 3]), array([9])]

In [12]:
#d
array = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
new_array = np.array_split(array,3)
new_array

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]])]

### 4. Searching elements in an array

In [13]:
#a
array = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(array == 4))

(array([3, 5, 6], dtype=int64),)


In [14]:
#b
array = np.array( [[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
print(np.where(array == 5))

(array([1], dtype=int64), array([1], dtype=int64))


In [15]:
#c
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Indices for odd elements: ",np.where(array%2 != 0))
print("Indices for even elements: ",np.where(array%2 == 0))

Indices for odd elements:  (array([0, 2, 4, 6], dtype=int64),)
Indices for even elements:  (array([1, 3, 5, 7], dtype=int64),)


### 5. Sorting of Arrays

In [16]:
#a
array = np.array([6, 5, 1, 2, 9, 10, 36, 7])
array = np.sort(array,axis=0)
print("Ascending order: ",array)
array = np.sort(array)[::-1]
print("Descending order",array)

Ascending order:  [ 1  2  5  6  7  9 10 36]
Descending order [36 10  9  7  6  5  2  1]


In [17]:
#b
array = np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])
array = np.sort(array,axis = 1)
print("Ascending order: ",array)
array = -np.sort(-array, axis=0)
print("Descending order",array)

Ascending order:  [[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
Descending order [[ 6  8 40]
 [ 3  7 10]
 [-2  5  7]]


### 6. Random number generation in NumPy arrays

In [18]:
#a
array = np.random.randint(0,21,6)
array

array([ 3,  9,  3, 20,  9, 19])

In [19]:
#b
array = np.random.rand(5)
array

array([0.12320643, 0.9186115 , 0.12302405, 0.39454266, 0.8903247 ])

In [20]:
#c
array = np.random.randint(50,size=(3,5))
array

array([[23,  3, 20, 25, 41],
       [21, 18, 39, 25, 13],
       [ 5, 19, 43, 39, 31]])

In [21]:
#d
array = np.random.rand(3,5)
array

array([[0.71597865, 0.14235623, 0.01553455, 0.51922227, 0.6131135 ],
       [0.08457051, 0.13342743, 0.32964465, 0.21898413, 0.8118962 ],
       [0.66034696, 0.60136699, 0.50013016, 0.2462805 , 0.35647858]])

In [22]:
#e
array = np.array([6, 5, 1, 2, 9, 10, 36, 7])
np.random.shuffle(array)
array


array([ 5,  1,  7, 10, 36,  9,  2,  6])

In [23]:
#f
array = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
np.random.shuffle(array)
array

array([[ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]])

# Part B

In [24]:
import pandas as pd
import csv

In [25]:
#1&2
#wine_data = pd.read_csv("/Users/Srikar/desktop/winequality.csv")
with open("/Users/Srikar/desktop/winequality.csv", 'r') as f:
    array = list(csv.reader(f, delimiter=";"))


In [26]:
#3
array = np.array(array[1:], dtype=np.float)
array

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [27]:
#4
array.shape

(1599, 12)

In [28]:
#5
#a
y = array[:,-1]
y.shape

(1599,)

In [29]:
#b
x = array[:,:-1]
x.shape

(1599, 11)

In [30]:
#6
#a
mean = x.mean(axis=0)
mean

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311])

In [31]:
#b
vals,counts = np.unique(y, return_counts=True)
index = np.argmax(counts)
print(vals[index])

5.0


In [32]:
#c
std = np.std(x,axis=None)
std

16.726533979432844